# This file was generated by GoReleaser. DO NOT EDIT.
class EcsAgentUpdater < Formula
  desc "update ECS agent with CLI."
  homepage "https://github.com/reiki4040/ecs-agent-updater"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/reiki4040/ecs-agent-updater/releases/download/v0.1.3/ecs-agent-updater_darwin_x86_64.tar.gz"
    sha256 "0eb33cbf954beda275e3846a55b1f23bf4ee46f4644c3031a559cfe1082f3b60"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/ecs-agent-updater/releases/download/v0.1.3/ecs-agent-updater_linux_x86_64.tar.gz"
      sha256 "737826dc68db1ec342a14446ec4760dc19451b814a547475962d976781f6c20e"
    end
  end

  def install
    bin.install "ecs-agent-updater"
  end
end
