# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserWork < Formula
  desc "show version info only."
  homepage "https://github.com/reiki4040/goreleaser-work"
  version "0.3.13"

  on_macos do
    on_intel do
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.13/goreleaser-work_darwin_x86_64.tar.gz"
      sha256 "331410623fe18dda1f1340ee87f4638db6e40b503f4794ca87b83ede97c21c72"

      def install
        bin.install "goreleaser-work"
      end
    end
    on_arm do
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.13/goreleaser-work_darwin_arm64.tar.gz"
      sha256 "44b211920632509663fe0f1468157fd935dc49fd2448f0b9ca284376865beaa0"

      def install
        bin.install "goreleaser-work"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.13/goreleaser-work_linux_x86_64.tar.gz"
        sha256 "720d2d935871b06ac98b4eb91f11e330b8d46d09969b8f1f6208123489e9948c"

        def install
          bin.install "goreleaser-work"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.13/goreleaser-work_linux_arm64.tar.gz"
        sha256 "4b5294a07c279ff91c3f0e1a4d6f6e67414501be053993bd03b0605c89e55630"

        def install
          bin.install "goreleaser-work"
        end
      end
    end
  end

  def caveats
    <<~EOS
      this message is shown on console when finished install with homebrew.
    EOS
  end
end
