# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserWork < Formula
  desc "show version info only."
  homepage "https://github.com/reiki4040/goreleaser-work"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.6/goreleaser-work_darwin_x86_64.tar.gz"
      sha256 "0f7497d337a2ac2a174fd07aac5c7aa0ae64efe076857ae00bd742791c48605f"

      def install
        bin.install "goreleaser-work"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.6/goreleaser-work_darwin_arm64.tar.gz"
      sha256 "278349c57edc83e552b2915456848e5f581457e34e0d4a2a4a02c1a0ce5a2476"

      def install
        bin.install "goreleaser-work"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.6/goreleaser-work_linux_x86_64.tar.gz"
      sha256 "e5b64244f0e337e79c4a85b11886a09b926943d15a62b4b7f005da132c7329bb"

      def install
        bin.install "goreleaser-work"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reiki4040/goreleaser-work/releases/download/v0.3.6/goreleaser-work_linux_arm64.tar.gz"
      sha256 "17fa91fec02f2965a9ba31c0065734cfa29bed3eb3b0b512d343074b5d45547e"

      def install
        bin.install "goreleaser-work"
      end
    end
  end

  def caveats
    <<~EOS
      this message is shown on console when finished install with homebrew.
    EOS
  end
end
