# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mogura < Formula
  desc "ssh tunneling tool"
  homepage "https://github.com/reiki4040/mogura"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reiki4040/mogura/releases/download/v0.2.4/mogura_darwin_arm64.tar.gz"
      sha256 "1ad51575a687e4f646c61d17a785d128b5f1d41c8c11a06266bf2330692a6aa1"

      def install
        bin.install "mogura"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/mogura/releases/download/v0.2.4/mogura_darwin_x86_64.tar.gz"
      sha256 "30917c7528fc3495ac01f1d8f373ccd5ccadf0d02b4fdf5a36a1fe48f1532b41"

      def install
        bin.install "mogura"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reiki4040/mogura/releases/download/v0.2.4/mogura_linux_arm64.tar.gz"
      sha256 "36640f8d2277217716350774432f01c1809f7f9a0682b53154e2c3ef3b2796b5"

      def install
        bin.install "mogura"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/mogura/releases/download/v0.2.4/mogura_linux_x86_64.tar.gz"
      sha256 "7f700d3071ca802ec166aa1d40419e3c2ed9065f4c26b9d5017e6128b97d422f"

      def install
        bin.install "mogura"
      end
    end
  end
end
