# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mogura < Formula
  desc "ssh tunneling tool"
  homepage "https://github.com/reiki4040/mogura"
  version "0.2.3"

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/reiki4040/mogura/releases/download/v0.2.3/mogura_darwin_x86_64.tar.gz"
    sha256 "6d5ed49d2015fb301881c29e7b0920537ab2470380a6b606063c96ac48bcb17a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/reiki4040/mogura/releases/download/v0.2.3/mogura_linux_x86_64.tar.gz"
    sha256 "b3601d18e11108e30a2bf5205c8e9c48054e2d3783bca11b9af580af3c40b122"
  end

  def install
    bin.install "mogura"
  end
end
