# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msk < Formula
  desc "assume role helper"
  homepage "https://github.com/reiki4040/msk"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/reiki4040/msk/releases/download/v0.1.3/msk_darwin_x86_64.tar.gz"
      sha256 "4ad0908e59c16cd131dcd6cc9d526d836ec0d2495aa9f09edeb038ff3ca47e51"

      def install
        bin.install "msk"
      end
    end
    on_arm do
      url "https://github.com/reiki4040/msk/releases/download/v0.1.3/msk_darwin_arm64.tar.gz"
      sha256 "93d7f8124f19ed1672a6ee96b4cc3bd7f8d07aecbaef157f61be8ad2f789d089"

      def install
        bin.install "msk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/msk/releases/download/v0.1.3/msk_linux_x86_64.tar.gz"
        sha256 "c784776afe73e97ef7b732d3ae21504f9af5bbeee608ec0eab1ab57c7c049201"

        def install
          bin.install "msk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/msk/releases/download/v0.1.3/msk_linux_arm64.tar.gz"
        sha256 "79a73d6ab64bad8ce070bb68ebbef8d5a4680d1cb581d1b20c3a738ad6ffee56"

        def install
          bin.install "msk"
        end
      end
    end
  end

  def caveats
    <<~EOS
      # msk is assume role helper!
    EOS
  end
end
