# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msk < Formula
  desc "assume role helper"
  homepage "https://github.com/reiki4040/msk"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/reiki4040/msk/releases/download/v0.1.2/msk_darwin_x86_64.tar.gz"
      sha256 "427f3c10d9b9c2ec71cdfb06e1b077825990a4f0519153ad19191444f1ba13b2"

      def install
        bin.install "msk"
      end
    end
    on_arm do
      url "https://github.com/reiki4040/msk/releases/download/v0.1.2/msk_darwin_arm64.tar.gz"
      sha256 "71565121eb6c738ebb483f63f340dc9bb0f6984b2d19059f18bb3b1dceffdb98"

      def install
        bin.install "msk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/msk/releases/download/v0.1.2/msk_linux_x86_64.tar.gz"
        sha256 "7ae6645de77b7ea3f255f2c70f207aeb3cf67a084c5941a2893040846951ae29"

        def install
          bin.install "msk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/msk/releases/download/v0.1.2/msk_linux_arm64.tar.gz"
        sha256 "5b229187b42ef57a91ac44b5bb07a58b18ec6afb45eae51e20c3921a55a2ec71"

        def install
          bin.install "msk"
        end
      end
    end
  end

  def caveats
    <<~EOS
      # msk is assume role helper!
    EOS
  end
end
