# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rnsd < Formula
  desc "control AWS Service Discovery command"
  homepage "https://github.com/reiki4040/rnsd"
  version "0.2.0"

  on_macos do
    url "https://github.com/reiki4040/rnsd/releases/download/v0.2.0/rnsd_Darwin_x86_64.tar.gz"
    sha256 "eb088a141a58c793899c0ad7684b936c9fa14751413f8f1cc939450774ffc1e0"

    def install
      bin.install "rnsd"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Rnsd
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/rnsd/releases/download/v0.2.0/rnsd_Linux_x86_64.tar.gz"
      sha256 "f595ac29604f98a56cb98e9f6865240c6be0cfc5aca43d41438aa1283ad775d3"

      def install
        bin.install "rnsd"
      end
    end
  end
end
