# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rnss < Formula
  desc "instance selection helper for aws ssm start-session"
  homepage "https://github.com/reiki4040/rnss"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/rnss/releases/download/v0.0.1/rnss_darwin_x86_64.tar.gz"
      sha256 "ab3a89364d66f04ff2b3646da453708bc2f83c338cab166f918b19376992416a"

      def install
        bin.install "rnss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reiki4040/rnss/releases/download/v0.0.1/rnss_darwin_arm64.tar.gz"
      sha256 "0252ccc3596c7183ac19e3666b1516a69c6fd83dc3a2b17c5bbd300be0d4ebfd"

      def install
        bin.install "rnss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/rnss/releases/download/v0.0.1/rnss_linux_x86_64.tar.gz"
      sha256 "a45496e80488278e0b18381e67c1ad49ebf760438b9d388d2d375bdfbfba87ac"

      def install
        bin.install "rnss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reiki4040/rnss/releases/download/v0.0.1/rnss_linux_arm64.tar.gz"
      sha256 "7af0898e9aa2eea4c83e8fb053ef448f3e8037e5541cc73ef87f206a24b864c2"

      def install
        bin.install "rnss"
      end
    end
  end

  def caveats
    <<~EOS
      # rnss required aws cli and session-manage-plugin in $PATH.
    EOS
  end
end
