# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rnssh < Formula
  desc "Easy ssh to EC2"
  homepage "https://github.com/reiki4040/rnssh"
  version "0.5.3"

  on_macos do
    on_intel do
      url "https://github.com/reiki4040/rnssh/releases/download/v0.5.3/rnssh_darwin_x86_64.tar.gz"
      sha256 "d934590283dfb618adeb080d170d736330062d113c30cb130186d8ab10dc3563"

      def install
        bin.install "rnssh"
      end
    end
    on_arm do
      url "https://github.com/reiki4040/rnssh/releases/download/v0.5.3/rnssh_darwin_arm64.tar.gz"
      sha256 "c151092c79d00d081416857d79df14904fdd173910eb32101fb2f729daf16f3a"

      def install
        bin.install "rnssh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/rnssh/releases/download/v0.5.3/rnssh_linux_x86_64.tar.gz"
        sha256 "f6cc3ae0e260bb0dbc2a2f5bd6fb47f44b21237cb84c35b497aee0468ce76315"

        def install
          bin.install "rnssh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/rnssh/releases/download/v0.5.3/rnssh_linux_arm64.tar.gz"
        sha256 "3faaacad467e38715d5ca67022b8ad7efb50d524fba017b684cbcf95ef4d8b68"

        def install
          bin.install "rnssh"
        end
      end
    end
  end

  def caveats
    <<~EOS
      # rnssh need AWS access key for working.
      # Please set key/secret to AWS credentials (~/.aws/credentials)

      [default]
      aws_access_key_id=your_key_id
      aws_secret_access_key=your_secret

      # or environment variable for AWS connection.
      # (~/.bashrc, ~/.zshrc or other.)

      export AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY

      # set default aws region.
      rnssh -init
    EOS
  end
end
