# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rnzoo < Formula
  desc "Useful tool for EC2."
  homepage "https://github.com/reiki4040/rnzoo"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.1/rnzoo_darwin_arm64.tar.gz"
      sha256 "100a4327f51d9fb94e7ae6d20e785f8bce51d796e2558734476a15cb2e406bfd"

      def install
        bin.install "rnzoo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.1/rnzoo_darwin_x86_64.tar.gz"
      sha256 "5f1e32760341226c3b9e4a57691fcfd2365fdf23d942b1d5bd9e75a4b5692d46"

      def install
        bin.install "rnzoo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.1/rnzoo_linux_arm64.tar.gz"
      sha256 "1b8cd76da757b21d729e438d74064aac2dc631c537ebf8a302da34bd681dabd9"

      def install
        bin.install "rnzoo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.1/rnzoo_linux_x86_64.tar.gz"
      sha256 "9673a7887293c2b1e343a8091db8ee73b92e36d54d22d522e64fecd2575c6edb"

      def install
        bin.install "rnzoo"
      end
    end
  end

  def caveats
    <<~EOS
      # rnzoo need AWS access key for working.
      # Please set key/secret to AWS credentials (~/.aws/credentials)

      [default]
      aws_access_key_id=your_key_id
      aws_secret_access_key=your_secret

      # or environment variable for AWS connection.
      # (~/.bashrc, ~/.zshrc or other.)

      export AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY

      # you can set default aws region.

      rnzoo init
    EOS
  end
end
