# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rnzoo < Formula
  desc "Useful tool for EC2."
  homepage "https://github.com/reiki4040/rnzoo"
  version "0.6.2"

  on_macos do
    on_intel do
      url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.2/rnzoo_darwin_x86_64.tar.gz"
      sha256 "2b8b1f7fa2c56ab99236f399cf06f1a4756c49e1e5c1e6aa7a0f015d85c0072d"

      def install
        bin.install "rnzoo"
      end
    end
    on_arm do
      url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.2/rnzoo_darwin_arm64.tar.gz"
      sha256 "b8d959354108d07800d53a8821f57867ecdb8dc93fe413f92a21d116c685a060"

      def install
        bin.install "rnzoo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.2/rnzoo_linux_x86_64.tar.gz"
        sha256 "94d3237ea027def793547c57176b583ec5bf429387ff546e3c1c36e322521d91"

        def install
          bin.install "rnzoo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/reiki4040/rnzoo/releases/download/v0.6.2/rnzoo_linux_arm64.tar.gz"
        sha256 "aa6d5bfeb76836114c351600c5e42144390984b7f3bea90c17499c91b1a19cc9"

        def install
          bin.install "rnzoo"
        end
      end
    end
  end

  def caveats
    <<~EOS
      # rnzoo need AWS access key for working.
      # Please set key/secret to AWS credentials (~/.aws/credentials)

      [default]
      aws_access_key_id=your_key_id
      aws_secret_access_key=your_secret

      # or environment variable for AWS connection.
      # (~/.bashrc, ~/.zshrc or other.)

      export AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY

      # you can set default aws region.

      rnzoo init
    EOS
  end
end
